# Generated by Django 4.1.3 on 2023-02-13 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drugpermission',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.drugunit'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.department'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.shipment'),
        ),
    ]
