# Generated by Django 4.1.3 on 2023-02-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_distribution_initial_amount_movement_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrugPermission',
        ),
    ]
