# Generated by Django 4.1.3 on 2023-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_delete_drugpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
