# Generated by Django 4.1.3 on 2023-02-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='drugs.direction'),
            preserve_default=False,
        ),
    ]
