# Generated by Django 4.1.3 on 2023-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_writeoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoff',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
